### ISSUE TITLE
Start command

### ISSUE THREAD

**Issue by CodeGeeks14** [AFoeee/VideoOnCommand#1]
I'm only able to activate a video command for streamer, mods, vips
i'm not allowed to set it to everyone. Is this available in stream element overlay?

**Comment by AFoeee** [comment]
hey @CodeGeeks14 

Which version of the widget do you use?
(If you're unsure, you can look it up in the overlay editor -> select said widget -> "Settings" -> "Open Editor" -> "Fields" Tab -> Scroll to the very end where it says "widgetVersion" -> "value" = version number.)

At least for the current version (the code that is shared in this repository) it seemed to work.

**Comment by CodeGeeks14** [comment]
Hi @AFoeee I checked but cant see widgetVersion...
I think it is the last one because i did take the one in the widget store of streamelements.
these are my only 3 options.
![image](https://user-images.githubusercontent.com/31842432/182375997-41b18ba5-27c9-4cbe-91b8-802b4987faac.png)

**Comment by AFoeee** [comment]
Ah kk, you got the very first version of the widget (by Benno).
This one didn't have an "Everyone" option.

You can find installation links to newer versions on the SE discord server -> channel: `#widget-share`.
(There is an invitation link to the discord server in the footer of the [SE website](https://streamelements.com/).)

The versions by Suerion or me do have said option.
